### PR TITLE
feat: implement automatic merging

### PR DESCRIPTION
**Pull request by bigboss2063**
In this pr, I did this things:
1. Based on @elliotchenzichang's suggestion, the data is being rewritten one by one to reduce the waiting time for user transactions.
2. The original "isMerging" field didn't effectively prevent multiple merges from running simultaneously, but I have fixed this issue now.
3. I have implemented automatic merging using a ticker, allowing users to set the interval for automatic merging in the configuration.
4. I have conducted some tests for automatic merging.

### CODE REVIEW

**Comment by bigboss2063** [comment]
There are some problem in reWriteData, I'm working on it.

**Comment by elliotchenzichang** [comment]
how fast so.. Honestly, you are the most powerful engineer I had ever seen.

**Comment by bigboss2063** [comment]
I‘m adding more unit tests for it.

**Comment by bigboss2063** [comment]
Unable to sleep at midnight, I got up to fix a bug 🤣. Finally, after so many fix commits, I managed to resolve the issue.

During the testing process, I noticed that running the merge goroutine concurrently with transactions could lead to a race condition. This happened when the merge goroutine was reading the index while a transaction was committing and modifying the same index. Using `-race` argment when testing can see error blow.
```bash
WARNING: DATA RACE
Write at 0x00c000074108 by goroutine 26:
  github.com/nutsdb/nutsdb.(*Record).UpdateRecord()
      /mnt/d/Projects/Go/nutsdb/record.go:43 +0x418
  github.com/nutsdb/nutsdb.(*BPTree).Insert()
      /mnt/d/Projects/Go/nutsdb/bptree.go:699 +0x485
  github.com/nutsdb/nutsdb.(*Tx).buildBPTreeIdx()
      /mnt/d/Projects/Go/nutsdb/tx.go:466 +0xafe
  github.com/nutsdb/nutsdb.(*Tx).Commit()
      /mnt/d/Projects/Go/nutsdb/tx.go:268 +0x10ce
  github.com/nutsdb/nutsdb.(*DB).managed()
      /mnt/d/Projects/Go/nutsdb/db.go:1004 +0x2aa
  github.com/nutsdb/nutsdb.(*DB).Update()
      /mnt/d/Projects/Go/nutsdb/db.go:325 +0x15b
  github.com/nutsdb/nutsdb.txPut()
      /mnt/d/Projects/Go/nutsdb/db_test.go:71 +0x70
  github.com/nutsdb/nutsdb.TestDB_MergeWithTx.func1.1()
      /mnt/d/Projects/Go/nutsdb/merge_test.go:99 +0x224

Previous read at 0x00c000074108 by goroutine 24:
  github.com/nutsdb/nutsdb.(*DB).merge()
      /mnt/d/Projects/Go/nutsdb/merge.go:105 +0x90e
  github.com/nutsdb/nutsdb.(*DB).mergeWorker()
      /mnt/d/Projects/Go/nutsdb/merge.go:169 +0x1f1
  github.com/nutsdb/nutsdb.open.func1()
      /mnt/d/Projects/Go/nutsdb/db.go:269 +0x39
```


To handle this, I had to use a transaction to complete the entire operation while rewriting an entry. However, since the checks to determine whether the read entry is the latest and whether it still exists in the index are all memory operations, the impact should be minimal.

**Comment by elliotchenzichang** [comment]
That's crazy, man.

**Review by elliotchenzichang — COMMENTED** [review]
LGTM. Thanks for this wonderful contributions

**Pull request merged**
