### PR TITLE
fix: check the list map instead of writing it

### PR DESCRIPTION
**Pull request by yudhasubki**
Hi Team,

This fixes https://github.com/nutsdb/nutsdb/issues/536.

Please see the example I've provided in https://github.com/nutsdb/nutsdb/issues/536

Kind Regards,

Yudha

### CODE REVIEW

**Comment by bigboss2063** [comment]
I checked our code, finding the API of sorted set have some problem. Do you mind fix it together?

**Comment by bigboss2063** [comment]
> I checked our code, finding the API of sorted set have some problem. Do you mind fix it together?

In tx_zset.go

**Comment by yudhasubki** [comment]
Updated @bigboss2063. sorry I thought it didn't impact on tx_zset.

**Review by bigboss2063 — APPROVED** [review]
LGTM! Thanks to your great work!

**Comment by bigboss2063** [comment]
Now your project should run normally 😁

**Pull request merged**
