### PR TITLE
test: add tests for IsDBClosed, IsPrefixScan and IsPrefixSearchScan

### PR DESCRIPTION
**Pull request by CodePrometheus**
Add some tests for IsDBClosed, IsPrefixScan and IsPrefixSearchScan in nutsdb/errors.go

### CODE REVIEW

**Comment by elliotchenzichang** [comment]
Hi~Seems something wrong with your unit tests, would you like to check it when you have time?

**Comment by CodePrometheus** [comment]
@elliotchenzichang It's caused by this issue #288, I've dealt with #289, take you some time to review, ths

**Comment by elliotchenzichang** [comment]
@CodePrometheus I had merged #289, we can retry this ci pipeline.

**Comment by CodePrometheus** [comment]
@elliotchenzichang yep, there should be no problem now

**Comment by elliotchenzichang** [comment]
> @elliotchenzichang yep, there should be no problem now

Would you like to rebase the master and push it again?  Seems that's the way to retry the ci pipeline.

**Comment by elliotchenzichang** [comment]
@CodePrometheus  hi～I retried the ci pipeline and still failed, would you like to check the code when you have time? Thanks in advance.

**Comment by CodePrometheus** [comment]
@elliotchenzichang yes, sorry for my mistake, take you a little time to check again, please

**Review by elliotchenzichang — COMMENTED** [review]
LGTM

**Comment by elliotchenzichang** [comment]
Merged it!Thanks for your contribution!

**Pull request merged**
