### PR TITLE
 Small scope refactoring code:move some util func to utils.go from db.go

### PR DESCRIPTION
**Pull request by damotiansheng**
Small scope refactoring code，move some common func to utils.go from db.go

### CODE REVIEW

**Comment by elliotchenzichang** [comment]
Hi, seems there are some conflicts in this PR. Could you help resolve them when you have time? Thanks!

**Comment by damotiansheng** [comment]
sure



---Original---
From: "Elliot ***@***.***&gt;
Date: Tue, Jul 25, 2023 22:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [nutsdb/nutsdb]  Small scope refactoring code:move some util functo utils.go from db.go (PR #379)




 
Hi, seems there are some conflicts in this PR. Could you help resolve them when you have time? Thanks!

**Comment by damotiansheng** [comment]
the conflicts have been resolved, pls check when you have any time

**Comment by elliotchenzichang** [comment]
Merge！ Thanks for this great contribution.

**Pull request merged**
