### PR TITLE
feat: Implement of increments and decrements

### PR DESCRIPTION
**Pull request by TremblingV5**
This PR is related with #517 and it contains `Incr`, `Dncr`, `IncrBy` and `DncrBy`.

The different methods rely on the same methods. The main logic as following:

1. Get value from bucket with checking if it has been expired
2. Try to convert value from string to int64. Use big int addition if it has over range of int64
3. Judge if the value will over range after addition. Use big int addition if yes.
4. Do addition as int64
5. Delete the old value and put the new value

And the follow is another proposal:

I think we can abstract a `Value` to replace `[]byte` of code. We can do more with `Value`, such as type assertion, more powerful additions when it's a numeric value and so on.

### CODE REVIEW

**Comment by bigboss2063** [comment]
You can open an issue to talk about your plans for Value in detail😁

**Comment by TremblingV5** [comment]
@bigboss2063 I have do some modifications for review. I will open an issue after refining my ideas about `Value`

**Review by bigboss2063 — APPROVED** [review]
LGTM. Thanks!

**Comment by bigboss2063** [comment]
Welcome to do more tasks!😁

**Pull request merged**
