### PR TITLE
feat: implement file lock

### PR DESCRIPTION
**Pull request by bigboss2063**
I implemented file lock by use [gofrs/flock](https://github.com/gofrs/flock).

### CODE REVIEW

**Comment by bigboss2063** [comment]
I forgot rerun the tests, there are some bugs.🤨

**Comment by elliotchenzichang** [comment]
> I forgot to rerun the tests, there are some bugs.🤨

No worries, Thanks for your quick action. Looking forward to the great PR when you fix the current issues.

**Comment by bigboss2063** [comment]
The bug from yesterday was caused by not creating the corresponding folder before acquiring the flock. 🤣
In the current test cases, only one db instance is used, and some tests do not call close after opening the database, resulting in some errors.

**Review by elliotchenzichang — COMMENTED** [review]
Does this PR considerated this scene? One db crash abnormally, and another db open the same path to recovery this instance.

**Review by elliotchenzichang — COMMENTED** [review]
LGTM. Thanks for this contribution!

**Pull request merged**
